module.exports = {
  arrowParens: 'always',
  printWidth: 90,
  singleQuote: true,
  trailingComma: 'all',
  semi: false,
  tabWidth: 2,
  useTabs: false,
  bracketSpacing: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  proseWrap: 'always',
  endOfLine: 'lf',
  insertPragma: false,
}
