#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running commit hooks..."

echo "Running lint command"
#npm run lint

echo "Running type-check command"
npm run type-check

echo "Running prettier command"
npm run prettier:fix

