name: Deploy
on: [ push ]

jobs:
  lint-and-test:
    name: Lint and Test Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: .github/scripts/lint-and-test.sh dev

  deploy-backend:
    name: Deploy Backend Stack
    runs-on: ubuntu-latest
    needs: [ lint-and-test ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: .github/scripts/deploy-backend.sh dev

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [ lint-and-test, deploy-backend ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: .github/scripts/build-frontend.sh dev
      - uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: backend/frontend-build/zip/dev/build.zip

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [ lint-and-test, deploy-backend, build-frontend ]
    concurrency:
      group: ${{ github.ref }}
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: eu-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/download-artifact@v2
        with:
          name: build.zip
          path: backend/frontend-builds/zip/dev
      - run: .github/scripts/setBranch.sh
      - run: .github/scripts/deploy-frontend.sh dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
