name: Deploy
on: [ push ]

jobs:
  build-lint-test:
    name: Lint, Test and Build Website
    runs-on: ubuntu-latest
    needs: [ set-env ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: .github/scripts/lint_test_build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: backend/build.zip

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ set-env, build-lint-test ]
    concurrency:
      group: ${{ github.ref }}
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: eu-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/download-artifact@v2
        with:
          name: build.zip
          path: backend
      - run: .github/scripts/setBranch.sh
      - run: .github/scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
