name: Deploy
on: [ push ]

jobs:
  build-website:
    name: Lint, Test and Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: .github/deploy/scripts/lint_test_build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: .github/deploy/build.zip

  test-cdk:
    name: Lint and Test CDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: .github/deploy/scripts/lint_test_build_cdk.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build-website, test-cdk ]
    concurrency:
      group: ${{ github.ref }}
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: eu-west-2
      DOMAIN_NAME: clubwoof.co.uk
      SUBDOMAIN_NAME: nextjs-serverless-static-site
    steps:
      - name: Configure AWS Credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::222743583620:user/github-workflow
          role-session-name: web_app_deploy_role
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/download-artifact@v2
        with:
          name: build.zip
          path: .github/deploy
      - run: .github/deploy/scripts/setBranch.sh
      - run: .github/deploy/scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
